admin_cms_node:
    path:     /
    defaults: { _controller: "CaravaneCmsBundle:Node:index" }

admin_cms_node_show:
    path:     /{id}/show
    defaults: { _controller: "CaravaneCmsBundle:Node:show" }

admin_cms_node_new:
    path:     /new
    defaults: { _controller: "CaravaneCmsBundle:Node:new" }

admin_cms_node_create:
    path:     /create
    defaults: { _controller: "CaravaneCmsBundle:Node:create" }
    methods:  POST

admin_cms_node_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaravaneCmsBundle:Node:edit" }

admin_cms_node_update:
    path:     /{id}/update
    defaults: { _controller: "CaravaneCmsBundle:Node:update" }
    methods:  [POST, PUT]

admin_cms_node_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaravaneCmsBundle:Node:delete" }
    methods:  [POST, DELETE]
