admin_cms_page:
    path:     /
    defaults: { _controller: "CaravaneCmsBundle:Page:index" }

admin_cms_page_show:
    path:     /{id}/show
    defaults: { _controller: "CaravaneCmsBundle:Page:show" }

admin_cms_page_new:
    path:     /new
    defaults: { _controller: "CaravaneCmsBundle:Page:new" }

admin_cms_page_create:
    path:     /create
    defaults: { _controller: "CaravaneCmsBundle:Page:create" }
    methods:  POST

admin_cms_page_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaravaneCmsBundle:Page:edit" }

admin_cms_page_update:
    path:     /{id}/update
    defaults: { _controller: "CaravaneCmsBundle:Page:update" }
    methods:  [POST, PUT]

admin_cms_page_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaravaneCmsBundle:Page:delete" }
    methods:  [POST, DELETE]
