admin_shop_product:
    path:     /
    defaults: { _controller: "CaravaneShopBundle:Product:index" }

admin_shop_product_show:
    path:     /{id}/show
    defaults: { _controller: "CaravaneShopBundle:Product:show" }

admin_shop_product_import:
    path:     /import
    defaults: { _controller: "CaravaneShopBundle:Product:import" }

admin_shop_product_new:
    path:     /new
    defaults: { _controller: "CaravaneShopBundle:Product:new" }

admin_shop_product_create:
    path:     /create
    defaults: { _controller: "CaravaneShopBundle:Product:create" }
    methods:  POST

admin_shop_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaravaneShopBundle:Product:edit" }

admin_shop_product_update:
    path:     /{id}/update
    defaults: { _controller: "CaravaneShopBundle:Product:update" }
    methods:  [POST, PUT]

admin_shop_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaravaneShopBundle:Product:delete" }
    methods:  [POST, DELETE]
