imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        shop_name: "%shop_name%"
        shop_baseline: "%shop_baseline%"
    form:
        resources:
            - 'bootstrap_3_layout.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    assets:
        font-awesome-otf:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/FontAwesome.otf'
            output: 'css/fonts/FontAwesome.otf'
        font-awesome-eot:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.eot'
            output: 'css/fonts/fontawesome-webfont.eot'
        font-awesome-svg:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.svg'
            output: 'css/fonts/fontawesome-webfont.svg'
        font-awesome-ttf:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.ttf'
            output: 'css/fonts/fontawesome-webfont.ttf'
        font-awesome-woff:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff'
            output: 'css/fonts/fontawesome-webfont.woff'
        glyphicons-halflings-regular-eot:
            inputs: '%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.eot'
            output: 'css/fonts/glyphicons-halflings-regular.eot'
        glyphicons-halflings-regular-ttf:
            inputs: '%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.ttf'
            output: 'css/fonts/glyphicons-halflings-regular.ttf'
        glyphicons-halflings-regular-svg:
            inputs: '%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.svg'
            output: 'css/fonts/glyphicons-halflings-regular.svg'
        glyphicons-halflings-regular-woff:
            inputs: '%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.woff'
            output: 'css/fonts/glyphicons-halflings-regular.woff'
    filters:
        #cssrewrite: ~
        less: # Nous importons ici nos variables
            node: %node_bin%
            node_paths: [%node_modules%]
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_translator:
                type: annotation
                prefix: Gedmo\Translator\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }

fos_user:
    db_driver: orm # other valid values are 'orm',mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Caravane\Bundle\UserBundle\Entity\User
    registration:
        confirmation:
            enabled:    true
    from_email:
        address:        "%shop_mail_sender_email%"
        sender_name:    "%shop_name%"
    service:
        mailer: fos_user.mailer.twig_swift

oneup_uploader:
    mappings:
        gallery:
            frontend: dropzone # or any uploader you use in the frontend

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            sluggable: true
            translatable: true
            timestampable: true
