caravane_cms:
    resource: "@CaravaneCmsBundle/Resources/config/routing.yml"
    prefix:   /

caravane_shop:
    resource: "@CaravaneShopBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation