services:
#    caravane_crm.example:
#        class: Caravane\Bundle\CrmBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    caravane_crm.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments: [ 'Crm', ['/','/crm', '/crm/category','/crm/contact'] ]
        tags:
            - { name: "doctrine_phpcr.initializer" }
