services:
    caravane_shop.phpcr.initializer.shop:
         class: Caravane\Bundle\ShopBundle\Initializer\ShopInitializer
         tags:
             - { name: doctrine_phpcr.initializer, priority: 60 }
    caravane_shop.product_manager:
        class: Caravane\Bundle\ShopBundle\Manager\ProductManager
        arguments: [@doctrine_phpcr.odm.default_document_manager]


    #caravane_shop.category_menu_provider:
    #        class: Symfony\Cmf\Bundle\MenuBundle\Provider\PhpcrMenuProvider
    #        arguments:
    #            - '@cmf_menu.factory'
    #            - '@doctrine_phpcr'
    #            - /shop/categories
    #        calls:
    #            - [setRequest, ["@?request="]]
    #        tags:
    #            - { name: knp_menu.provider }
