services:
    caravane_shop.phpcr.initializer.shop:
         class: Caravane\Bundle\ShopBundle\Initializer\ShopInitializer
         tags:
             - { name: doctrine_phpcr.initializer, priority: 60 }
    caravane_shop.product_manager:
        class: Caravane\ShopBundle\Manager\ProductManager
        arguments: [@doctrine.orm.entity_manager]
